# 配置rocketmq
rocketmq:
  name-server: xxx:9876;xxx:9876
  producer:
    group: dubbo-demo-service-manager-producer-group-1 #生产者
  consumer:
    group: dubbo-demo-service-manager-consumer-group-1 #消费者

server:
  port: 8096

spring:
  application:
    name: rocketmq-demo-server
